### ISSUE TITLE
[Question] Add vuetify

### ISSUE THREAD

**Issue by xcesaralejandro** [mudrd8mz/moodle-tool_vuejsdemo#1]
How can add vuetify to my vue project? i download vuetify from cdn and import like vue but i recive in console: `No define call for vue`

**Comment by adpe** [comment]
Hello @xcesaralejandro 

I was looking in to this plugin and it has a lot of limits as you can not work with `.vue` files as `Single File Component(s)`. Nevertheless, I tried something look@https://github.com/adpe/moodle-tool_vuejsdemo, which would include Vuetify but you can not work proper with the components.

I suggest using https://github.com/MartinGauk/moodle-mod_vuejsdemo as initial situation and transfer it to the wanted Moodle `plugintype`.

There are several plugins which has this base:
* https://github.com/lucaboesch/moodle-local_differentiator
* https://github.com/kulmann/moodle-mod_philosophers
* https://github.com/kulmann/moodle-mod_millionaire

HTH,
Adrian

PS: I would close this issue @mudrd8mz

**Comment by xcesaralejandro** [comment]
@adpe Thank you very much, he managed to clarify some doubts that I still had.
